[package]
name = "github-clone-server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
actix-files = "0.6"
actix-cors = "0.6"
serde = { version = "1.0", features = ["derive"] }
tempfile = "3.2"
git2 = "0.13"
log = "0.4"
log4rs = { version = "1.2", features = ["yaml_format", "yaml_config"] }
chrono = "0.4"
