[package]
name = "github-clone-server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
serde = { version = "1.0", features = ["derive"] }
tempfile = "3.2"
git2 = "0.13"
uuid = { version = "0.8", features = ["v4"] }
