name: Upload OpenAPI spec to Stainless and (Mintlify) docs repo

on:
  push:
    branches: [main]
    paths:
      - 'openapi.json'
  workflow_dispatch:

jobs:
  stainless:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Push documented spec to docs repo
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'openapi.json'
          destination_repo: 'robmck1995/mintlify-docs'
          user_email: 'rmcknight451@gmail.com'
          user_name: 'robmck1995'
          commit_message: 'Updated openapi.json from lsproxy'
