name: Upload OpenAPI spec and Docs to Mintlify
on:
  push:
    branches: [main]
    paths:
      - 'openapi.json'
      - 'README.md'
  workflow_dispatch:
jobs:
  upload-openapi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Push documented spec to docs repo
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'openapi.json'
          destination_repo: 'robmck1995/mintlify-docs'
          user_email: 'rmcknight451@gmail.com'
          user_name: 'robmck1995'
          commit_message: 'Updated openapi.json from lsproxy'

  upload-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Push README to docs repo as introduction.mdx
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'README.md'
          destination_file: 'get-started/introduction.mdx'
          destination_repo: 'robmck1995/mintlify-docs'
          user_email: 'rmcknight451@gmail.com'
          user_name: 'robmck1995'
          commit_message: 'Updated introduction.mdx from lsproxy README'
