name: OpenAPI Spec Check

on:
  pull_request:
    paths:
      - 'lsproxy/src/**/*.rs'
      - 'openapi.json'

jobs:
  check-spec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t lsproxy-dev -f Dockerfile.dev .

      - name: Generate fresh OpenAPI spec
        run: |
          mkdir -p temp_spec
          docker run --name temp_lsp_box -v "$(pwd)/temp_spec":/usr/src/app lsproxy-dev ./lsproxy -w
          docker rm temp_lsp_box

      - name: Compare specs
        run: |
          if ! diff -u openapi.json temp_spec/openapi.json; then
            echo "::error::OpenAPI spec is out of sync with code! Please run ./scripts/generate_spec.sh"
            echo "::error::See diff above for details"
            exit 1
          fi
