name: Upload OpenAPI spec to Stainless and (Mintlify) docs repo

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  stainless:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Push spec and config to Stainless and output documented spec
        uses: stainless-api/upload-openapi-spec-action@main
        with:
          stainless_api_key: ${{ secrets.STAINLESS_API_KEY }}
          input_path: 'openapi.json'
          output_path: 'openapi.documented.json'
          project_name: 'lsproxy'
          guess_config: true
      - name: Push documented spec to docs repo
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'openapi.documented.json'
          destination_repo: 'robmck1995/mintilify-docs'
          user_email: 'rmcknight451@gmail.com' # the email associated with the GH token
          user_name: 'robmck1995' # the username associated with the GH token
          commit_message: 'Auto-updates from Stainless'
